#!/bin/bash

if [ "$1" = "build" ] || [ "$1" = "push" ]; then
	if [ "$1" = "push" ];then
		pushArg="--push"
	fi
	DOCKER_BUILDKIT=1 docker buildx build \
		$pushArg \
		--platform linux/arm/v7,linux/amd64 \
		--tag pabloortiz132/platform:latest \
		./
	exit
fi

if [ "$1" = "setup-ubuntu" ]; then
	./cli/bash/setup-ubuntu.sh
	exit
fi

# Run CLI
if [ "$CI_MODE" = "1" ]; then
	ttyArgs=''
else
	ttyArgs='-ti'
fi

hash=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 20 | head -1)

if [ "$1" = "test-panel" ];then
	shift
	docker run --rm $ttyArgs \
		--user $(id -u):$(stat -c %g /var/run/docker.sock) \
		-v $PWD/../HomePanel:/project \
		-v $PWD/cli:/cli \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-v ~/.gitconfig:/etc/gitconfig \
		-e PROJECT_DIR=$PWD/../HomePanel \
		-e CI_MODE=$CI_MODE \
		-e CLI_DEV="1" \
		--network host \
		--name homepanel-platform-$hash \
		pabloortiz132/platform \
		$@
	exit
fi

if [ "$1" = "test-parkink" ];then
	shift
	export PLATFORM_NETWORK=$(docker network ls | grep -oh 'parkink_web[^ ]*')	
	docker run --rm $ttyArgs \
		--user $(id -u):$(stat -c %g /var/run/docker.sock) \
		-v $PWD/../parkink-platform:/project \
		-v $PWD/cli:/cli \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-v ~/.gitconfig:/etc/gitconfig \
		-e PROJECT_DIR=$PWD/../parkink-platform \
		-e PLATFORM_NETWORK=$PLATFORM_NETWORK \
		-e CI_MODE=$CI_MODE \
		-e BIND_IP=127.0.0.1: \
		--network host \
		--name parkink-platform-$hash \
		pabloortiz132/platform \
		$@
	exit
fi